name = "captmichaeldev-portfolio-v2-astro"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js/index.js"
assets = { directory = "./dist", binding = "ASSETS" }
